"""Control work attempt 1.

Revision ID: 1ffb7e30a2d8
Revises: 
Create Date: 2021-12-30 18:43:36.938973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffb7e30a2d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_code', sa.String(length=10), nullable=False),
    sa.Column('organization_name', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('contract_amount', sa.Float(), nullable=True),
    sa.Column('contract_type', sa.Enum('one_sided', 'two_sided', 'many_sided', name='contracttypes'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_contracts_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    op.drop_table('contracts')
    # ### end Alembic commands ###
