"""empty message

Revision ID: 7e3956515292
Revises: 7a9a1f4e95bb
Create Date: 2023-01-17 00:54:33.139946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3956515292'
down_revision = '7a9a1f4e95bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('about_me', sa.TEXT(), nullable=True),
    sa.Column('usertype', sa.VARCHAR(length=13), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    # ### end Alembic commands ###
