"""cw new db3

Revision ID: 84a0623847aa
Revises: afd3087d3658
Create Date: 2021-12-31 05:10:54.471443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a0623847aa'
down_revision = 'afd3087d3658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractypes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_contractypes_type'), ['type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractypes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_contractypes_type'), type_='unique')

    # ### end Alembic commands ###
