"""empty message

Revision ID: 89bfd9c0b91c
Revises: 12ee330b76ce
Create Date: 2023-01-21 22:28:32.906760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bfd9c0b91c'
down_revision = '12ee330b76ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contractypes')
    op.drop_table('orders')
    op.drop_table('contracts')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=70),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=70),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=70),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('contracts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contract_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('organization_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('deadline', sa.DATE(), nullable=False),
    sa.Column('contract_amount', sa.FLOAT(), nullable=True),
    sa.Column('contract_type', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['contract_type'], ['contractypes.type_id'], name='fk_contracts_contract_type_contractypes'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_contracts_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_contracts'),
    sa.UniqueConstraint('contract_code', name='uq_contracts_contract_code')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('order', sa.VARCHAR(length=50), nullable=False),
    sa.Column('variety', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('card_code', sa.INTEGER(), nullable=True),
    sa.Column('number_phone', sa.VARCHAR(length=14), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_orders')
    )
    op.create_table('contractypes',
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('type_id', name='pk_contractypes'),
    sa.UniqueConstraint('type', name='uq_contractypes_type')
    )
    # ### end Alembic commands ###
