"""lab 13 att 4

Revision ID: 98968b7ec86c
Revises: 0caa4e714a0c
Create Date: 2021-12-31 15:07:10.056467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98968b7ec86c'
down_revision = '0caa4e714a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_posts_post_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_posts_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_post_id_user', 'user', ['post_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
