"""empty message

Revision ID: a3155be5b4a8
Revises: fa73f991b982
Create Date: 2023-01-16 23:53:24.230325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3155be5b4a8'
down_revision = 'fa73f991b982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('contract_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_phone', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('usertype', sa.Enum('User', 'Moderator', 'Administrator', name='usertype'), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('usertype')
        batch_op.drop_column('number_phone')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('contract_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('deadline',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    op.create_table('_alembic_tmp_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_category'),
    sa.UniqueConstraint('name', name='uq_category_name')
    )
    # ### end Alembic commands ###
