"""cw new db

Revision ID: afd3087d3658
Revises: 1ffb7e30a2d8
Create Date: 2021-12-31 04:06:42.308553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd3087d3658'
down_revision = '1ffb7e30a2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractypes',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('type_id', name=op.f('pk_contractypes'))
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_contracts_contract_code'), ['contract_code'])
        batch_op.create_foreign_key(batch_op.f('fk_contracts_contract_type_contractypes'), 'contractypes', ['contract_type'], ['type_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contracts_contract_type_contractypes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_contracts_contract_code'), type_='unique')

    op.drop_table('contractypes')
    # ### end Alembic commands ###
